#!/bin/bash

# Edit this file to introduce tasks to be run by cron.
#
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
#
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').#
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
#
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
#
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
#
# For more information see the manual pages of crontab(5) and cron(8)
#
# m h  dom mon dow   command


########### MORNING RUN ######################
40 15 * * * ssh -i ~/.ssh/google_compute_engine 35.232.245.138 exit
41 15 * * * python ~/create_instance.py seq.cfg 0 asto-seq0 >> ~/LOGS/morning0.log 
41 15 * * * python ~/create_instance.py nsw.cfg 0 asto-nsw0 >> ~/LOGS/nswm0.log 
41 15 * * * python ~/create_instance.py vic.cfg 0 asto-vic0 >> ~/LOGS/vicm0.log 
41 15 * * * python ~/create_instance.py tas.cfg 0 asto-tas0 >> ~/LOGS/morning0.log 

50 15 * * * ssh -i ~/.ssh/google_compute_engine 35.232.245.138 exit
10 16 * * * python ~/create_instance.py seq.cfg 1 asto-seq1 >> ~/LOGS/morning1.log 
10 16 * * * python ~/create_instance.py nsw.cfg 1 asto-nsw1 >> ~/LOGS/nswm1.log
10 16 * * * python ~/create_instance.py vic.cfg 1 asto-vic1 >> ~/LOGS/vicm1.log
10 16 * * * python ~/create_instance.py tas.cfg 1 asto-tas1 >> ~/LOGS/tas1.log

#50 16 * * * ssh -i ~/.ssh/google_compute_engine 35.232.245.138 exit
#51 16 * * * python ~/create_instance.py seq.cfg 2 asto-seq2 >> ~/LOGS/morning2.log 
#51 16 * * * python ~/create_instance.py nsw.cfg 2 asto-nsw2 >> ~/LOGS/nswm2.log 
#51 16 * * * python ~/create_instance.py vic.cfg 2 asto-vic2 >> ~/LOGS/vicm2.log


00 17 * * * ssh -i ~/.ssh/google_compute_engine 35.232.245.138 exit
#51 17 * * * python ~/create_instance.py seq.cfg 2 asto-seq2 >> ~/LOGS/morning2.log 
01 17 * * * python ~/create_instance.py nsw.cfg 3 asto-nsw3 >> ~/LOGS/nswm3.log 
01 17 * * * python ~/create_instance.py vic.cfg 3 asto-vic3 >> ~/LOGS/vicm3.log
01 17 * * * python ~/create_instance.py tas.cfg 3 asto-tas3 >> ~/LOGS/tasm3.log

30 17 * * * ssh -i ~/.ssh/google_compute_engine 35.232.245.138 exit
32 17 * * * python ~/create_instance.py seq.cfg 6 asto-seq6 >> ~/LOGS/morning6.log 

########## ARVO RUN #################################

40 03 * * * ssh -i ~/.ssh/google_compute_engine 35.232.245.138 exit
41 03 * * * python ~/create_instance.py seq.cfg 1 asto-seq1 >> ~/LOGS/arvo1.log 
41 03 * * * python ~/create_instance.py nsw.cfg 1 asto-nsw1 >> ~/LOGS/nswa1.log
41 03 * * * python ~/create_instance.py vic.cfg 1 asto-vic1 >> ~/LOGS/vica1.log
41 03 * * * python ~/create_instance.py tas.cfg 1 asto-tas1 >> ~/LOGS/tasa1.log

10 04 * * * ssh -i ~/.ssh/google_compute_engine 35.232.245.138 exit
11 04 * * * python ~/create_instance.py seq.cfg 3 asto-seq3 >> ~/LOGS/arvo3.log 


########## MOVE DAYS ###########################
00 14 * * * ~/move_days

