#!/bin/bash

# Edit this file to introduce tasks to be run by cron.
#
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
#
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').#
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
#
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
#
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
#
# For more information see the manual pages of crontab(5) and cron(8)
#
# m h  dom mon dow   command


########### MORNING RUN ######################
40 15 * * * ssh 104.196.228.245 exit
41 15 * * * python ~/create_instance.py seq.cfg 0 asto-seq0 >> ~/LOGS/morning0.log 
50 15 * * * ssh 104.196.228.245 exit
51 15 * * * python ~/create_instance.py seq.cfg 1 asto-seq1 >> ~/LOGS/morning1.log 
50 15 * * * ssh 104.196.228.245 exit
51 15 * * * python ~/create_instance.py seq.cfg 2 asto-seq2 >> ~/LOGS/morning2.log 
50 16 * * * ssh 104.196.228.245 exit
31 16 * * * python ~/create_instance.py seq.cfg 6 asto-seq6 >> ~/LOGS/morning6.log 


########## ARVO RUN #################################

40 03 * * * ssh 104.196.228.245 exit
41 03 * * * python ~/create_instance.py seq.cfg 1 asto-seq1 >> ~/LOGS/arvo1.log 
00 04 * * * ssh 104.196.228.245 exit
01 04 * * * python ~/create_instance.py seq.cfg 3 asto-seq3 >> ~/LOGS/arvo3.log 


########## MOVE DAYS ###########################
00 14 * * * ~/move_days

